// DO NOT EDIT - generated by tools/scripts/gen_effect_registry.py
import type {AnimationComponent, AnimationMeta} from './effects-types';
import Fade from '@pack-rendering-elements-animations/fade/component?astrid=9219e6b273d8';
import FadeUp from '@pack-rendering-elements-animations/fade-up/component?astrid=b8034f42c7ba';
import ScaleIn from '@pack-rendering-elements-animations/scale-in/component?astrid=8e81bd16b46e';
import SlideLeft from '@pack-rendering-elements-animations/slide-left/component?astrid=c811f132f349';
import SlideUp from '@pack-rendering-elements-animations/slide-up/component?astrid=d3797d38de54';
import TypeOn from '@pack-rendering-elements-animations/type-on/component?astrid=866889901fd3';

export const ACTIVE_THEME_ID = null;
export const ANIMATION_IDS = ['fade', 'fade-up', 'scale-in', 'slide-left', 'slide-up', 'type-on'] as const;
export type AnimationId = typeof ANIMATION_IDS[number];
export const ANIMATION_REGISTRY: Record<AnimationId, AnimationComponent> = {
  'fade': Fade,
  'fade-up': FadeUp,
  'scale-in': ScaleIn,
  'slide-left': SlideLeft,
  'slide-up': SlideUp,
  'type-on': TypeOn,
};
export const ANIMATION_DEFAULTS: Record<AnimationId, Record<string, unknown>> = {
  'fade': {"durationFrames":12},
  'fade-up': {"durationFrames":18},
  'scale-in': {"durationFrames":18},
  'slide-left': {"durationFrames":18},
  'slide-up': {"durationFrames":12},
  'type-on': {"durationFraction":0.55,"durationFrames":120,"showCaret":true,"startFrame":18},
};
export const ANIMATION_META: Record<AnimationId, AnimationMeta> = {
  'fade': {"defaultDurationFrames":12,"id":"fade","kind":"wrapper","name":"Fade","pack_id":"rendering","phase":["entrance","exit"]},
  'fade-up': {"defaultDurationFrames":18,"id":"fade-up","kind":"wrapper","name":"Fade Up","pack_id":"rendering","phase":"entrance"},
  'scale-in': {"defaultDurationFrames":18,"id":"scale-in","kind":"wrapper","name":"Scale In","pack_id":"rendering","phase":"entrance"},
  'slide-left': {"defaultDurationFrames":18,"id":"slide-left","kind":"wrapper","name":"Slide Left","pack_id":"rendering","phase":"entrance"},
  'slide-up': {"defaultDurationFrames":12,"id":"slide-up","kind":"wrapper","name":"Slide Up","pack_id":"rendering","phase":"exit"},
  'type-on': {"defaultDurationFrames":120,"id":"type-on","kind":"hook","name":"Type On","pack_id":"rendering","phase":"entrance"},
};
export const ANIMATION_FINGERPRINTS: Record<AnimationId, string> = {
  'fade': '9219e6b273d87948f9b77bdbc20dd438df12f50a3cec49e22990eac417fc5e65',
  'fade-up': 'b8034f42c7ba583a93a48abe49e3b6ba3e5e8632bc37ff1d492f1563918607dc',
  'scale-in': '8e81bd16b46e6eb2bff75134434ea6b321216b67e55c16f24d12e460050dc9ac',
  'slide-left': 'c811f132f3495d2c5ed03606b5b49e641eee4246697ad0fcf3bca0500ac9883f',
  'slide-up': 'd3797d38de545d3ea8e2446ceeede743009ddcb33a8ecd96a822991282df9a75',
  'type-on': '866889901fd3c5082a0562bbb40afda247b3b1b14aeb63a58071bcb3f4843f13',
};
