// DO NOT EDIT - generated by tools/scripts/gen_effect_registry.py
import type {AnimationComponent, AnimationMeta} from './effects-types';
import Fade from '@pack-builtin-elements-animations/fade/component';
import FadeUp from '@pack-builtin-elements-animations/fade-up/component';
import ScaleIn from '@pack-builtin-elements-animations/scale-in/component';
import SlideLeft from '@pack-builtin-elements-animations/slide-left/component';
import SlideUp from '@pack-builtin-elements-animations/slide-up/component';
import TypeOn from '@pack-builtin-elements-animations/type-on/component';

export const ACTIVE_THEME_ID = null;
export const ANIMATION_IDS = ['fade', 'fade-up', 'scale-in', 'slide-left', 'slide-up', 'type-on'] as const;
export type AnimationId = typeof ANIMATION_IDS[number];
export const ANIMATION_REGISTRY: Record<AnimationId, AnimationComponent> = {
  'fade': Fade,
  'fade-up': FadeUp,
  'scale-in': ScaleIn,
  'slide-left': SlideLeft,
  'slide-up': SlideUp,
  'type-on': TypeOn,
};
export const ANIMATION_DEFAULTS: Record<AnimationId, Record<string, unknown>> = {
  'fade': {"durationFrames":12},
  'fade-up': {"durationFrames":18},
  'scale-in': {"durationFrames":18},
  'slide-left': {"durationFrames":18},
  'slide-up': {"durationFrames":12},
  'type-on': {"durationFraction":0.55,"durationFrames":120,"showCaret":true,"startFrame":18},
};
export const ANIMATION_META: Record<AnimationId, AnimationMeta> = {
  'fade': {"defaultDurationFrames":12,"id":"fade","kind":"wrapper","name":"Fade","pack_id":"builtin","phase":["entrance","exit"]},
  'fade-up': {"defaultDurationFrames":18,"id":"fade-up","kind":"wrapper","name":"Fade Up","pack_id":"builtin","phase":"entrance"},
  'scale-in': {"defaultDurationFrames":18,"id":"scale-in","kind":"wrapper","name":"Scale In","pack_id":"builtin","phase":"entrance"},
  'slide-left': {"defaultDurationFrames":18,"id":"slide-left","kind":"wrapper","name":"Slide Left","pack_id":"builtin","phase":"entrance"},
  'slide-up': {"defaultDurationFrames":12,"id":"slide-up","kind":"wrapper","name":"Slide Up","pack_id":"builtin","phase":"exit"},
  'type-on': {"defaultDurationFrames":120,"id":"type-on","kind":"hook","name":"Type On","pack_id":"builtin","phase":"entrance"},
};
