// DO NOT EDIT - generated by tools/scripts/gen_effect_registry.py
import type {EffectComponent} from './effects-types';
import AudioReactiveColour from '@pack-rendering-elements-effects/audio-reactive-colour/component?astrid=7ff374791489';
import ModelTrends from '@pack-local-elements-effects/model-trends/component?astrid=df431aef3985';
import NeonOrbitCard from '@pack-local-elements-effects/neon-orbit-card/component?astrid=8084647a0c27';
import SlidingMedia from '@pack-local-elements-effects/sliding-media/component?astrid=7af5fc9bafd6';
import TextCard from '@pack-local-elements-effects/text-card/component?astrid=e9740bbfa84a';
import VibeComfyAssetOverlay from '@pack-local-elements-effects/vibe-comfy-asset-overlay/component?astrid=08c5c6160b0c';
import VibeComfyBumper from '@pack-local-elements-effects/vibe-comfy-bumper/component?astrid=8b2593e9ed64';

export const ACTIVE_THEME_ID = null;
export const EFFECT_IDS = ['audio-reactive-colour', 'model-trends', 'neon-orbit-card', 'sliding-media', 'text-card', 'vibe-comfy-asset-overlay', 'vibe-comfy-bumper'] as const;
export type EffectId = typeof EFFECT_IDS[number];
export const EFFECT_REGISTRY: Record<EffectId, EffectComponent> = {
  'audio-reactive-colour': AudioReactiveColour,
  'model-trends': ModelTrends,
  'neon-orbit-card': NeonOrbitCard,
  'sliding-media': SlidingMedia,
  'text-card': TextCard,
  'vibe-comfy-asset-overlay': VibeComfyAssetOverlay,
  'vibe-comfy-bumper': VibeComfyBumper,
};
export const CLIP_TYPE_ALIASES: Record<string, EffectId> = {
  'sliding-media': 'sliding-media',
  text: 'text-card',
  'vibe-comfy-asset-overlay': 'vibe-comfy-asset-overlay',
  'vibe-comfy-bumper': 'vibe-comfy-bumper',
};
export const EFFECT_FINGERPRINTS: Record<EffectId, string> = {
  'audio-reactive-colour': '7ff3747914892040b1456c2ec4f59a44fef534aa46b3d5ad9d902cb8b67c8249',
  'model-trends': 'df431aef3985c4304cc0eeef6460e2e86824b4a4b0ba72ece39b60a1a338f0aa',
  'neon-orbit-card': '8084647a0c27094559e57d4bc553dbfa66c09c20670963c220ca2aaee822a3d0',
  'sliding-media': '7af5fc9bafd6e1b15978545e5f7ca7d924d4dae0de8715db90375ecf9cf809f7',
  'text-card': 'e9740bbfa84a22a2c7ce3375467b80d3b5d17a9bf70d018f418ac224cb426d45',
  'vibe-comfy-asset-overlay': '08c5c6160b0c7072bc8cbecaf444f1028207c30fe71d58e6794b44ce4053794b',
  'vibe-comfy-bumper': '8b2593e9ed64324e736a43e8ff2bbb751614bd4ff6527c9fcf1b522065dcdba8',
};
