// DO NOT EDIT - generated by tools/scripts/gen_effect_registry.py
import type {TransitionComponent} from './effects-types';
import CrossFade from '@pack-builtin-elements-transitions/cross-fade/component';
import Fade from '@pack-builtin-elements-transitions/fade/component';

export const ACTIVE_THEME_ID = null;
export const TRANSITION_IDS = ['cross-fade', 'fade'] as const;
export type TransitionId = typeof TRANSITION_IDS[number];
export const TRANSITION_REGISTRY: Record<TransitionId, TransitionComponent> = {
  'cross-fade': CrossFade,
  'fade': Fade,
};
export const TRANSITION_DEFAULTS: Record<TransitionId, Record<string, unknown>> = {
  'cross-fade': {"durationFrames":8},
  'fade': {"durationFrames":8},
};
export const TRANSITION_META: Record<TransitionId, Record<string, unknown>> = {
  'cross-fade': {"id":"cross-fade","label":"Cross Fade","pack_id":"builtin"},
  'fade': {"id":"fade","label":"Fade","pack_id":"builtin"},
};
