// DO NOT EDIT - generated by tools/scripts/gen_effect_registry.py
import type {TransitionComponent} from './effects-types';
import CrossFade from '@pack-rendering-elements-transitions/cross-fade/component?astrid=c712b89cb887';
import Fade from '@pack-rendering-elements-transitions/fade/component?astrid=964a9b198603';

export const ACTIVE_THEME_ID = null;
export const TRANSITION_IDS = ['cross-fade', 'fade'] as const;
export type TransitionId = typeof TRANSITION_IDS[number];
export const TRANSITION_REGISTRY: Record<TransitionId, TransitionComponent> = {
  'cross-fade': CrossFade,
  'fade': Fade,
};
export const TRANSITION_DEFAULTS: Record<TransitionId, Record<string, unknown>> = {
  'cross-fade': {"durationFrames":8},
  'fade': {"durationFrames":8},
};
export const TRANSITION_META: Record<TransitionId, Record<string, unknown>> = {
  'cross-fade': {"id":"cross-fade","label":"Cross Fade","pack_id":"rendering"},
  'fade': {"id":"fade","label":"Fade","pack_id":"rendering"},
};
export const TRANSITION_FINGERPRINTS: Record<TransitionId, string> = {
  'cross-fade': 'c712b89cb887b531283adfd22b37a3d6c25a41137fe85c044a8fe44175aa8add',
  'fade': '964a9b1986035cfc6d64117c51d103be3c86aad27f0a8a98b2c18ad8d5319930',
};
