// DO NOT EDIT - generated by tools/scripts/gen_effect_registry.py
import type {TransitionComponent} from './effects-types';
import CrossFade from '@managed-elements-transitions/cross-fade/component';
import Fade from '@managed-elements-transitions/fade/component';

export const ACTIVE_THEME_ID = "banodoco-default" as const;
export const TRANSITION_IDS = ['cross-fade', 'fade'] as const;
export type TransitionId = typeof TRANSITION_IDS[number];
export const TRANSITION_REGISTRY: Record<TransitionId, TransitionComponent> = {
  'cross-fade': CrossFade,
  'fade': Fade,
};
export const TRANSITION_DEFAULTS: Record<TransitionId, Record<string, unknown>> = {
  'cross-fade': {"durationFrames":8},
  'fade': {"durationFrames":8},
};
export const TRANSITION_META: Record<TransitionId, Record<string, unknown>> = {
  'cross-fade': {"dependencies":{"js_packages":[],"python_requirements":[]},"id":"cross-fade","label":"Cross Fade"},
  'fade': {"dependencies":{"js_packages":[],"python_requirements":[]},"id":"fade","label":"Fade"},
};
